### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by koossaayy** [Noisyboy-9/laravel_blog#1]
Hey, nice project you have here, Good Job . 
However I have few things to say: About the Login/Logout controllers, how about making them in one controller, say AuthController. 
Also about the validation of the password in the register form request, 
instead of using min and max, have a look at this : https://laravel-news.com/password-validation-rule-object-in-laravel-8

**Comment by Noisyboy-9** [comment]
Hi @koossaayy
tnx for the review and suggestions I really appreciate that.
I have made separate Login/Logout/Register Controllers on purpose, cause I'm a strong believer of the fact that it is better to try to avoid custom actions in controllers as much as possible, as Adam Wathan, too have described in the Laracon of 2017 :
https://www.youtube.com/watch?v=MF0jFKvS4SI&t=106s
although it bears mentioning that this project is too small and choosing either approach won't make any difference at all, and even Jeffry himself uses a AuthController himself, when he is coding this project in his laracasts series.
For the password validation rules, it is awesome! I wasn't aware of such thing even exist! I will refactor the code to use this new validation rule which makes live much easier.
again, tnx for the time you consisted to the review I very much appreciate that.

**Comment by koossaayy** [comment]
Hey @Noisyboy-9 
True, it's a small project and it doesn't make any difference, but what I like here is the mindset, I mean training about those kind of stuff, will make you able to structure larger projects easily. 
Good job friend and Good luck

**Comment by Noisyboy-9** [comment]
@koossaayy 
tnx man I'm very happy you have liked it, it made my day 😁🙏
